// Code generated by MockGen. DO NOT EDIT.
// Source: pgconn.go

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	reflect "reflect"

	db "github.com/gictorbit/mabna/db"
	gomock "github.com/golang/mock/gomock"
	pgxpool "github.com/jackc/pgx/v5/pgxpool"
)

// MockFinanceDatabase is a mock of FinanceDatabase interface.
type MockFinanceDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockFinanceDatabaseMockRecorder
}

// MockFinanceDatabaseMockRecorder is the mock recorder for MockFinanceDatabase.
type MockFinanceDatabaseMockRecorder struct {
	mock *MockFinanceDatabase
}

// NewMockFinanceDatabase creates a new mock instance.
func NewMockFinanceDatabase(ctrl *gomock.Controller) *MockFinanceDatabase {
	mock := &MockFinanceDatabase{ctrl: ctrl}
	mock.recorder = &MockFinanceDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinanceDatabase) EXPECT() *MockFinanceDatabaseMockRecorder {
	return m.recorder
}

// GetLatestTrades mocks base method.
func (m *MockFinanceDatabase) GetLatestTrades(ctx context.Context) ([]db.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestTrades", ctx)
	ret0, _ := ret[0].([]db.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestTrades indicates an expected call of GetLatestTrades.
func (mr *MockFinanceDatabaseMockRecorder) GetLatestTrades(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestTrades", reflect.TypeOf((*MockFinanceDatabase)(nil).GetLatestTrades), ctx)
}

// GetPgConn mocks base method.
func (m *MockFinanceDatabase) GetPgConn() *pgxpool.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPgConn")
	ret0, _ := ret[0].(*pgxpool.Pool)
	return ret0
}

// GetPgConn indicates an expected call of GetPgConn.
func (mr *MockFinanceDatabaseMockRecorder) GetPgConn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPgConn", reflect.TypeOf((*MockFinanceDatabase)(nil).GetPgConn))
}
